"""Bounded reconciliation of existing Radar deliveries, never a Research executor.

Runs/artifacts record intent. Existing validators own source qualification.
No provider fallback, date rewriting, historical-membership invention or rerun.
"""
from __future__ import annotations
import argparse
import json
import os
import re
import runpy
import subprocess
from datetime import datetime, time, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

REPOSITORY = "auguspp/decision-kernel"
WORKFLOW = "stock-reading-after-sector.yml"
SECTOR = "sector-radar-shadow.yml"
STOCK = "hithink-stock-dump-trial.yml"
ISSUE = 581
MAX_SOURCE_ATTEMPTS = 3
MAX_RECOVERY_RUNS = 40
TZ = ZoneInfo("Asia/Shanghai")
NOOP = "VALIDATED_ALREADY_CURRENT_NO_PROSPECTIVE_EVENT"
SHA = re.compile(r"[0-9a-f]{40}\Z")


def check(ok, code):
    if not ok:
        raise ValueError(code)


def clock(value):
    value = datetime.fromisoformat(value.replace("Z", "+00:00"))
    check(value.tzinfo is not None, "AWARE_CLOCK_REQUIRED")
    return value


def source_retryable(operation):
    """Only anchored diagnostics generated by our transport, never source prose."""
    if not isinstance(operation, dict):
        return False
    msg = operation.get("error_message", "")
    if not isinstance(msg, str):
        return False
    return bool(re.match(
        r"^HiThink request or response decoding failed for /api/[a-zA-Z0-9/_-]+; "
        r"failure_kind=(?:TIMEOUT|URL_ERROR); elapsed_ms=(?:[0-9]+|None)$", msg
    ) or re.match(
        r"^failure_kind=HTTP_OTHER; elapsed_ms=(?:[0-9]+|None); "
        r"HiThink HTTP request failed for /api/[a-zA-Z0-9/_-]+ with status (?:502|503|504)(?:;|$)", msg
    ))


def choose(snapshot, now):
    """Pure plan. Market dates come from producer/reader, not weekday arithmetic."""
    local = now.astimezone(TZ)
    out = {"version": "radar-delivery-reconciliation-v1", "checked_at": now.isoformat(),
           "code_sha": snapshot["code_sha"], "reconciliation_run_id": snapshot["run_id"],
           "status": "CHECK_INCOMPLETE", "action": None, "open_gap": True,
           "investment_authority": "NONE", "research_authority": "NONE",
           "max_source_attempts_per_cycle": MAX_SOURCE_ATTEMPTS}
    if snapshot.get("active"):
        return dict(out, status="WAITING_FOR_ACTIVE_WORK", active_run_ids=snapshot["active"])
    lane = snapshot["sector"]
    saved = lane.get("last_qualified_result")
    validation = lane.get("latest_state_validation") or saved
    out.update(pending_delivery={"lane": "sector", "target": local.date().isoformat()},
               market_session=(saved or {}).get("market_session"),
               sector_run_id=(saved or {}).get("run", {}).get("id"),
               latest_sector_attempt=lane.get("latest_attempt"))
    if lane.get("health") in {"CHECK_INCOMPLETE", "LATEST_SUCCESS_INPUT_REJECTED"}:
        return dict(out, status="SECTOR_READ_REJECTED", gaps=lane.get("gaps", []))
    if not saved or lane.get("reading_copy_kind") != "VERIFIED_SAVED_PRODUCT":
        return dict(out, status="SECTOR_BASELINE_UNAVAILABLE", gaps=lane.get("gaps", []))
    out["sector_checked_at"] = validation["run"]["created_at"]
    floor = datetime.combine(local.date(), time(15, 30), tzinfo=TZ)
    verified_today = floor <= clock(validation["run"]["created_at"]) <= now
    todays = [r for r in snapshot["sector_runs"] if clock(r["created_at"]) >= floor]
    latest = max(snapshot["sector_runs"], key=lambda r: (clock(r["created_at"]), r["id"]), default=None)
    if not verified_today and local.weekday() < 5 and time(15, 30) <= local.time() < time(18, 35):
        return dict(out, status="WAITING_FOR_PRIMARY_CAPTURE")
    if not verified_today and local.weekday() < 5 and local.time() >= time(18, 35):
        if len(todays) >= MAX_SOURCE_ATTEMPTS:
            return dict(out, status="SOURCE_ATTEMPT_BUDGET_EXHAUSTED")
        if latest and latest.get("conclusion") != "success":
            if not snapshot.get("source_retryable", False):
                return dict(out, status="SOURCE_FAILURE_REQUIRES_ENGINEERING", gaps=lane.get("gaps", []))
            if now - clock(latest.get("updated_at", latest["created_at"])) < timedelta(minutes=2):
                return dict(out, status="WAITING_FOR_SOURCE_COOLDOWN")
        action = {"lane": "sector", "workflow": SECTOR,
                  "target": local.date().isoformat(), "inputs": {"operation": "produce"}}
    else:
        out["pending_delivery"] = {"lane": "stock", "target": str(saved["run"]["id"])}
        if saved.get("status") == NOOP or "SAME_SESSION_RESULT_NOT_FOUND_IN_BOUNDED_QUERY" in lane.get("gaps", []):
            return dict(out, status="RESULT_BEARING_SECTOR_DELIVERY_UNAVAILABLE")
        stock_lane = snapshot["stock"]
        stock = stock_lane.get("last_qualified_result") or {}
        out.update(stock_run_id=stock.get("run", {}).get("id"), stock_coverage=stock.get("coverage"),
                   stock_parent=snapshot.get("stock_parent"))
        if stock_lane.get("health") in {"CHECK_INCOMPLETE", "LATEST_SUCCESS_INPUT_REJECTED"}:
            return dict(out, status="STOCK_READ_REJECTED", gaps=stock_lane.get("gaps", []))
        if (stock_lane.get("reading_copy_kind") == "VERIFIED_SAVED_PRODUCT"
                and snapshot.get("stock_parent") == str(saved["run"]["id"])):
            partial = stock.get("coverage", {}).get("scope_complete") is False
            return dict(out, status="UP_TO_DATE_WITH_ISSUER_GAPS" if partial else "UP_TO_DATE",
                        open_gap=partial, pending_delivery=None, gaps=stock_lane.get("gaps", []))
        marker = f"stock-reading | sector={saved['run']['id']} | page=base |"
        if any(r.get("display_title", "").startswith(marker) for r in snapshot["stock_runs"]):
            return dict(out, status="EXISTING_STOCK_ATTEMPT_REQUIRES_RECONCILIATION")
        action = {"lane": "stock", "workflow": STOCK, "target": str(saved["run"]["id"]),
                  "inputs": {"trial-purpose": "stock-reading", "stock-market-run-id": str(saved["run"]["id"])}}
    # Intent is uploaded BEFORE dispatch. Absence of a child is uncertainty.
    for old in snapshot.get("intents", []):
        a = old.get("action") or {}
        if a.get("lane") != action["lane"] or a.get("target") != action["target"]:
            continue
        key = a.get("inputs", {}).get("recovery-key")
        check(isinstance(key, str) and bool(key), "PRIOR_INTENT_KEY_MISSING")
        runs = snapshot["sector_runs"] if action["lane"] == "sector" else snapshot["stock_runs"]
        matches = [r for r in runs if r.get("display_title", "").endswith(" | recovery=" + key)]
        if not matches and old.get("dispatch_occurred") is not False:
            return dict(out, status="UNRECONCILED_DISPATCH_INTENT", intent_run_id=old.get("reconciliation_run_id"))
    if not snapshot.get("main_ci_ready"):
        return dict(out, status="WAITING_FOR_CURRENT_MAIN_CI")
    key = f"radar-{action['lane']}-{action['target']}-{snapshot['run_id']}"
    action["inputs"]["recovery-key"] = key
    return dict(out, status="RECOVERY_PLANNED", action=action)


def run_page(api, workflow, limit=40):
    data = api.get(f"actions/workflows/{workflow}/runs?branch=main&per_page={limit}")
    rows = data.get("workflow_runs")
    check(isinstance(rows, list) and (rows or data.get("total_count") == 0), "RUN_PAGE_INCOMPLETE")
    check(len(rows) <= limit, "RUN_PAGE_BOUND")
    return rows, data.get("total_count", 0)


def active_work(api):
    activity = runpy.run_path(str(Path(__file__).with_name("check-sector-scheduled-activity.py")))
    paths = frozenset({f".github/workflows/{SECTOR}", f".github/workflows/{STOCK}",
                       ".github/workflows/decision-inbox.yml", ".github/workflows/live-dogfood.yml"})
    return activity["check_activity"](activity["request_reader"](os.environ.get("GH_TOKEN", "")), peers=paths)


def collect(api, root, now):
    from decision_kernel.runtime import current_state as model
    from decision_kernel.runtime.current_state_delivery import Collector
    code = os.environ["GITHUB_SHA"]
    check(SHA.fullmatch(code) is not None, "EXACT_CODE_REQUIRED")
    check(api.get("git/ref/heads/main")["object"]["sha"] == code, "MAIN_MOVED")
    result = {"code_sha": code, "run_id": os.environ["GITHUB_RUN_ID"], "active": active_work(api)}
    if result["active"]:
        return result
    collector = Collector(api, code, root, now=lambda: now.isoformat())
    sector_runs, complete = collector.runs("sector")
    sector_runs = [r for r in sector_runs if model.select_runs([r], "sector")[0] is not None]
    check(complete, "SECTOR_RUN_QUERY_INCOMPLETE")
    sector = collector.lane("sector")
    stock_runs, complete = collector.runs("stock")
    check(complete, "STOCK_RUN_QUERY_INCOMPLETE")
    stock = collector.lane("stock")
    result.update(sector_runs=sector_runs, sector=sector, stock_runs=stock_runs, stock=stock,
                  stock_parent=None, source_retryable=False, intents=[])
    prior_stock = stock.get("last_qualified_result") or {}
    binding = prior_stock.get("details", {}).get("market-context-binding.json")
    if binding and binding["read_path"] in collector.files:
        result["stock_parent"] = str(json.loads(collector.files[binding["read_path"]])["run_id"])
    latest = sector.get("latest_attempt") or {}
    operation = latest.get("operation") or {}
    result["source_retryable"] = source_retryable(operation)
    if latest.get("conclusion") == "failure" and operation.get("status") == "FAILURE_DETAIL_UNAVAILABLE_NOT_QUIET":
        jobs = api.get(f"actions/runs/{latest['id']}/jobs?per_page=100")
        check(jobs["total_count"] == len(jobs["jobs"]), "FAILURE_JOB_QUERY_INCOMPLETE")
        for job in jobs["jobs"]:
            failed = [s["name"] for s in job.get("steps", []) if s.get("conclusion") == "failure"]
            if failed == ["Check shared-Key activity once before acquisition"]:
                log = subprocess.run(["gh", "run", "view", str(latest["id"]), "--repo", REPOSITORY,
                                      "--job", str(job["id"]), "--log"], capture_output=True, text=True, check=True).stdout
                check(len(log) <= 2 * 1024 * 1024, "PREFLIGHT_LOG_BOUND")
                result["source_retryable"] = bool(re.search(
                    r"(?:^|\s)(?:GITHUB_ACTIVITY_RESPONSE_INCOMPLETE|BLOCKED_SHARED_KEY_ACTIVITY)(?:\s|$)", log))
    ci, _ = run_page(api, "ci.yml", 40)
    eligible = [r for r in ci if r.get("head_sha") == code and r.get("event") == "push"]
    latest_ci = max(eligible, key=lambda r: (clock(r["created_at"]), r["id"]), default={})
    result["main_ci_ready"] = (latest_ci.get("status") == "completed"
                               and latest_ci.get("conclusion") == "success" and latest_ci.get("run_attempt") == 1)
    runs, count = run_page(api, WORKFLOW, MAX_RECOVERY_RUNS)
    floor = datetime.combine(now.astimezone(TZ).date() - timedelta(days=3), time.min, tzinfo=TZ)
    check(count <= len(runs) or (runs and min(clock(r["created_at"]) for r in runs) < floor),
          "RECOVERY_INTENT_QUERY_INCOMPLETE")
    for run in runs:
        if str(run["id"]) == result["run_id"] or clock(run["created_at"]) < floor:
            continue
        if run.get("run_attempt") != 1 or run.get("head_repository", {}).get("full_name") != REPOSITORY:
            continue
        artifacts = collector.artifacts(run)
        intent = [a for a in artifacts if a.get("name") == f"radar-reconcile-intent-{run['id']}"]
        check(len(intent) <= 1, "DUPLICATE_RECONCILIATION_INTENT")
        if not intent:
            continue
        files, _ = collector.archive(intent[0], run)
        check(set(files) == {"plan.json"}, "INTENT_FILES_INVALID")
        old = json.loads(files["plan.json"])
        check(str(old.get("reconciliation_run_id")) == str(run["id"])
              and old.get("code_sha") == run["head_sha"], "INTENT_IDENTITY_INVALID")
        reports = [a for a in artifacts if a.get("name") == f"radar-reconcile-report-{run['id']}"]
        check(len(reports) <= 1, "DUPLICATE_RECONCILIATION_REPORT")
        if reports:
            output, _ = collector.archive(reports[0], run)
            receipt = json.loads(output["report.json"])
            check(str(receipt.get("reconciliation_run_id")) == str(run["id"])
                  and receipt.get("code_sha") == run["head_sha"], "REPORT_IDENTITY_INVALID")
            if (receipt.get("status") == "NOT_DISPATCHED_PRECHECK_CHANGED"
                    and receipt.get("dispatch_occurred") is False
                    and receipt.get("intent_key") == old["action"]["inputs"]["recovery-key"]):
                old["dispatch_occurred"] = False
        result["intents"].append(old)
    return result


def dispatch(plan, api):
    check(plan.get("status") == "RECOVERY_PLANNED" and plan.get("action"), "DISPATCH_PLAN_REQUIRED")
    check(plan["code_sha"] == os.environ["GITHUB_SHA"]
          and str(plan["reconciliation_run_id"]) == os.environ["GITHUB_RUN_ID"], "DISPATCH_IDENTITY_CHANGED")
    action = plan["action"]
    intent_key = action["inputs"]["recovery-key"]
    if api.get("git/ref/heads/main")["object"]["sha"] != plan["code_sha"] or active_work(api):
        return dict(plan, status="NOT_DISPATCHED_PRECHECK_CHANGED", action=None,
                    dispatch_occurred=False, intent_key=intent_key, open_gap=True)
    expected = {"sector": (SECTOR, {"operation", "recovery-key"}),
                "stock": (STOCK, {"trial-purpose", "stock-market-run-id", "recovery-key"})}
    wf, keys = expected[action["lane"]]
    check(action["workflow"] == wf and set(action["inputs"]) == keys, "DISPATCH_SCOPE_INVALID")
    if action["lane"] == "sector":
        check(action["inputs"]["operation"] == "produce", "SOURCE_OPERATION_INVALID")
    else:
        check(action["inputs"]["trial-purpose"] == "stock-reading"
              and re.fullmatch(r"[1-9][0-9]{0,19}", action["inputs"]["stock-market-run-id"]), "STOCK_INPUT_INVALID")
    payload = json.dumps({"ref": "main", "inputs": action["inputs"]})
    reply = subprocess.run(["gh", "api", "--include", "--method", "POST",
                            f"repos/{REPOSITORY}/actions/workflows/{wf}/dispatches", "--input", "-"],
                           input=payload, capture_output=True, text=True)
    accepted = reply.returncode == 0 and bool(re.search(r"HTTP/\S+ 204\b", reply.stdout))
    return dict(plan, status="DISPATCH_ACCEPTED_AWAITING_RESULT" if accepted else "DISPATCH_UNCERTAIN",
                open_gap=True, action=None, dispatched_action=action, intent_key=intent_key,
                dispatch_occurred=True if accepted else None)


def retain_unresolved(previous, report):
    """A newer successful day does not erase an older missing Stock delivery."""
    pending = {}
    for row in previous.get("unresolved_deliveries", []):
        check(isinstance(row, dict) and row.get("lane") in {"sector", "stock"}
              and re.fullmatch(r"[0-9-]{1,20}", str(row.get("target", ""))), "HEALTH_HISTORY_INVALID")
        pending[(row["lane"], row["target"])] = row
    row = report.get("pending_delivery")
    if row:
        pending.setdefault((row["lane"], row["target"]), {
            **row, "first_seen": report["checked_at"], "run_id": report["reconciliation_run_id"]})
    for key in list(pending):
        lane, target = key
        if lane == "stock" and report.get("stock_parent") == target:
            del pending[key]
        elif lane == "sector" and report.get("sector_checked_at"):
            checked = clock(report["sector_checked_at"]).astimezone(TZ)
            if ((report.get("market_session") or "") >= target
                    or (checked.date().isoformat() == target and checked.time() >= time(15, 30))):
                del pending[key]
    check(len(pending) <= 32, "UNRESOLVED_DELIVERY_BOUND_REQUIRES_ENGINEERING")
    return dict(report, unresolved_deliveries=list(pending.values()),
                open_gap=bool(pending) or report.get("open_gap", True))


def report_issue(report):
    prior = subprocess.run(["gh", "api", f"repos/{REPOSITORY}/issues/{ISSUE}"],
                           capture_output=True, text=True, check=True)
    body = json.loads(prior.stdout)["body"]
    start, end = "<!-- radar-continuity-status-v1 -->", "<!-- /radar-continuity-status-v1 -->"
    previous = {}
    if start in body:
        check(body.count(start) == body.count(end) == 1, "HEALTH_HISTORY_MARKER_INVALID")
        previous = json.loads(body.split(start, 1)[1].split(end, 1)[0])
    report = retain_unresolved(previous, report)
    body = ("# 日常数据连续性（系统状态，不是投资待办）\n\n最近对账状态：**" + report["status"] + "**。\n\n"
            + "```json\n" + json.dumps(report, ensure_ascii=False, indent=2) + "\n```\n\n"
            + start + json.dumps(report, ensure_ascii=False, separators=(",", ":")) + end + "\n\n"
            + "已有结果不重采；失败不是无变化。单股缺口不触发整批重跑。未解决的历史交付保留，"
            + "不会因另一交易日成功自动删除。历史输入和价格口径需要工程处理时，不要求Human手工填价。\n\n"
            + f"[本次对账](https://github.com/{REPOSITORY}/actions/runs/{report['reconciliation_run_id']})"
            + " · [执行路线图](https://github.com/auguspp/decision-kernel/issues/297)\n\n"
            + "本Issue仅机器健康投影；Human评论不改。AI Investment Authority=NONE。")
    payload = {"title": "[OPS] 日常数据连续性｜" + report["status"], "body": body,
               "state": "open" if report.get("open_gap", True) else "closed"}
    subprocess.run(["gh", "api", "--method", "PATCH", f"repos/{REPOSITORY}/issues/{ISSUE}", "--input", "-"],
                   input=json.dumps(payload), text=True, stdout=subprocess.DEVNULL, check=True)
    return report


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=["plan", "dispatch", "report"])
    parser.add_argument("--output", type=Path, default=Path("radar-reconcile"))
    args = parser.parse_args()
    args.output.mkdir(exist_ok=True)
    now = datetime.now(timezone.utc)
    from decision_kernel.runtime.current_state_delivery import GitHubAPI
    api = GitHubAPI(os.environ.get("GH_TOKEN", ""), max_calls=240)
    report = {"version": "radar-delivery-reconciliation-v1", "checked_at": now.isoformat(),
              "code_sha": os.environ.get("GITHUB_SHA"), "reconciliation_run_id": os.environ.get("GITHUB_RUN_ID"),
              "status": "CHECK_INCOMPLETE", "action": None, "open_gap": True}
    try:
        check(os.environ.get("GITHUB_REPOSITORY") == REPOSITORY
              and os.environ.get("GITHUB_REF") == "refs/heads/main"
              and os.environ.get("GITHUB_RUN_ATTEMPT") == "1", "FRESH_MAIN_RECONCILIATION_REQUIRED")
        if args.mode == "plan":
            report = choose(collect(api, Path.cwd(), now), now)
            (args.output / "plan.json").write_text(json.dumps(report, ensure_ascii=False, sort_keys=True))
            if os.environ.get("GITHUB_OUTPUT"):
                with open(os.environ["GITHUB_OUTPUT"], "a") as f:
                    f.write("dispatch=" + ("true" if report.get("action") else "false") + "\n")
        elif args.mode == "dispatch":
            report = dispatch(json.loads((args.output / "plan.json").read_text()), api)
        else:
            file = args.output / "report.json"
            if file.exists():
                report = json.loads(file.read_text())
            if os.environ.get("RECONCILE_MODE") != "audit":
                report = report_issue(report)
                file.write_text(json.dumps(report, ensure_ascii=False, indent=2))
            return 0
    except Exception as exc:
        report.update(status="CHECK_INCOMPLETE", action=None, open_gap=True, error_type=type(exc).__name__)
        if type(exc) is ValueError and re.fullmatch(r"[A-Z_]{3,100}", str(exc)):
            report["error_code"] = str(exc)
    (args.output / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2))
    print(json.dumps(report, ensure_ascii=False))
    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as f:
            f.write("## Daily Radar reconciliation\n\n```json\n" + json.dumps(report, ensure_ascii=False, indent=2) + "\n```\n")
    return 1 if report["status"] in {"CHECK_INCOMPLETE", "DISPATCH_UNCERTAIN"} else 0


if __name__ == "__main__":
    raise SystemExit(main())
